---
all:
  children:
    rhel_10:
      hosts: {}
      vars:
        os_major: "10"
    rhel_9:
      hosts: {}
      vars:
        os_major: "9"
    rhel_8:
      hosts: {}
      vars:
        os_major: "8"

  vars:
    ansible_user: svc_ansible_linux
    ansible_become: true
    ansible_become_method: sudo
