---
# roles/rhel_patching/tasks/cleanup.yml

- name: "Cleanup | Remove orphaned dependencies"
  ansible.builtin.dnf:
    autoremove: true
  when: enable_autoremove | bool

- name: "Cleanup | Clean DNF cache"
  ansible.builtin.command:
    cmd: dnf clean all
  changed_when: false
